
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.minebound.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;

import net.minecraft.world.level.block.Block;

import net.mcreator.minebound.block.YellowGlowRockBlock;
import net.mcreator.minebound.block.WoodenLogBlock;
import net.mcreator.minebound.block.WetDirtBlock;
import net.mcreator.minebound.block.WasteBlock;
import net.mcreator.minebound.block.VineBlockBlock;
import net.mcreator.minebound.block.UnrefinedMudstoneBlock;
import net.mcreator.minebound.block.UnrefinedLimestoneBlock;
import net.mcreator.minebound.block.UnrefinedGritstoneBlock;
import net.mcreator.minebound.block.UnrefinedGneissBlock;
import net.mcreator.minebound.block.UnrefinedDaciteBlock;
import net.mcreator.minebound.block.UnrefinedConglomerateBlock;
import net.mcreator.minebound.block.UnrefinedChertBlock;
import net.mcreator.minebound.block.UnrefinedArkoseBlock;
import net.mcreator.minebound.block.UnrefinedAndesiteBlock;
import net.mcreator.minebound.block.ThicksnowBlock;
import net.mcreator.minebound.block.TheblockBlock;
import net.mcreator.minebound.block.TextureBlock;
import net.mcreator.minebound.block.TestRedstoneOnBlock;
import net.mcreator.minebound.block.TestRedstoneOffBlock;
import net.mcreator.minebound.block.TestPressurePlateBlock;
import net.mcreator.minebound.block.TestLightOnBlock;
import net.mcreator.minebound.block.TestLightOffBlock;
import net.mcreator.minebound.block.TestLightBlockBlock;
import net.mcreator.minebound.block.TestDoorBlock;
import net.mcreator.minebound.block.TestButtonBlock;
import net.mcreator.minebound.block.TentacleClusterBlock;
import net.mcreator.minebound.block.TarTestBlock;
import net.mcreator.minebound.block.TarBlock;
import net.mcreator.minebound.block.StripedWoodBlock;
import net.mcreator.minebound.block.StonerubbleBlock;
import net.mcreator.minebound.block.SpaceFluidBlock;
import net.mcreator.minebound.block.SmoothiceBlock;
import net.mcreator.minebound.block.SmoothcobblestoneBlock;
import net.mcreator.minebound.block.SlushBlock;
import net.mcreator.minebound.block.SlimeGlobBlock;
import net.mcreator.minebound.block.SlidyNothingBlock;
import net.mcreator.minebound.block.SandBlock;
import net.mcreator.minebound.block.RoughsandstoneBlock;
import net.mcreator.minebound.block.PoisonBlock;
import net.mcreator.minebound.block.PlantMatterBlock;
import net.mcreator.minebound.block.PackedBonesBlock;
import net.mcreator.minebound.block.OrbitalPortalBlock;
import net.mcreator.minebound.block.ObsidianBlock;
import net.mcreator.minebound.block.MudBlock;
import net.mcreator.minebound.block.MoonstoneBlock;
import net.mcreator.minebound.block.MoonrockBlock;
import net.mcreator.minebound.block.MoonDustBlock;
import net.mcreator.minebound.block.MeteoriterockBlock;
import net.mcreator.minebound.block.MagmarockBlock;
import net.mcreator.minebound.block.LoosesiltBlock;
import net.mcreator.minebound.block.LimestoneBlock;
import net.mcreator.minebound.block.JunkpileBlock;
import net.mcreator.minebound.block.JellyblobBlock;
import net.mcreator.minebound.block.IcematerialBlock;
import net.mcreator.minebound.block.IceblockBlock;
import net.mcreator.minebound.block.HiveblockBlock;
import net.mcreator.minebound.block.HigherPortalBlock;
import net.mcreator.minebound.block.GraniteRockBlock;
import net.mcreator.minebound.block.GeodestoneBlock;
import net.mcreator.minebound.block.GeodecrystalsBlock;
import net.mcreator.minebound.block.FrozendirtBlock;
import net.mcreator.minebound.block.FleshpileBlock;
import net.mcreator.minebound.block.FleshchunkBlock;
import net.mcreator.minebound.block.DrysandBlock;
import net.mcreator.minebound.block.DrydirtBlock;
import net.mcreator.minebound.block.DirtmaterialBlock;
import net.mcreator.minebound.block.DirestoneBlock;
import net.mcreator.minebound.block.CorruptdirtBlock;
import net.mcreator.minebound.block.CoreLavaBlock;
import net.mcreator.minebound.block.CoarsegravelBlock;
import net.mcreator.minebound.block.CloudBlock;
import net.mcreator.minebound.block.ClayBlock;
import net.mcreator.minebound.block.BrainsBlock;
import net.mcreator.minebound.block.BlueglowrockBlock;
import net.mcreator.minebound.block.BlaststoneBlock;
import net.mcreator.minebound.block.AshBlock;
import net.mcreator.minebound.block.AlienrockBlock;
import net.mcreator.minebound.MineboundMod;

public class MineboundModBlocks {
	public static final DeferredRegister<Block> REGISTRY = DeferredRegister.create(ForgeRegistries.BLOCKS, MineboundMod.MODID);
	public static final RegistryObject<Block> HIGHER_PORTAL = REGISTRY.register("higher_portal", () -> new HigherPortalBlock());
	public static final RegistryObject<Block> POISON = REGISTRY.register("poison", () -> new PoisonBlock());
	public static final RegistryObject<Block> TEXTURE = REGISTRY.register("texture", () -> new TextureBlock());
	public static final RegistryObject<Block> ORBITAL_PORTAL = REGISTRY.register("orbital_portal", () -> new OrbitalPortalBlock());
	public static final RegistryObject<Block> TEST_LIGHT_BLOCK = REGISTRY.register("test_light_block", () -> new TestLightBlockBlock());
	public static final RegistryObject<Block> TEST_BUTTON = REGISTRY.register("test_button", () -> new TestButtonBlock());
	public static final RegistryObject<Block> TEST_DOOR = REGISTRY.register("test_door", () -> new TestDoorBlock());
	public static final RegistryObject<Block> TEST_PRESSURE_PLATE = REGISTRY.register("test_pressure_plate", () -> new TestPressurePlateBlock());
	public static final RegistryObject<Block> TEST_LIGHT_OFF = REGISTRY.register("test_light_off", () -> new TestLightOffBlock());
	public static final RegistryObject<Block> TEST_LIGHT_ON = REGISTRY.register("test_light_on", () -> new TestLightOnBlock());
	public static final RegistryObject<Block> TEST_REDSTONE_OFF = REGISTRY.register("test_redstone_off", () -> new TestRedstoneOffBlock());
	public static final RegistryObject<Block> TEST_REDSTONE_ON = REGISTRY.register("test_redstone_on", () -> new TestRedstoneOnBlock());
	public static final RegistryObject<Block> ALIENROCK = REGISTRY.register("alienrock", () -> new AlienrockBlock());
	public static final RegistryObject<Block> ASH = REGISTRY.register("ash", () -> new AshBlock());
	public static final RegistryObject<Block> BLASTSTONE = REGISTRY.register("blaststone", () -> new BlaststoneBlock());
	public static final RegistryObject<Block> BLUEGLOWROCK = REGISTRY.register("blueglowrock", () -> new BlueglowrockBlock());
	public static final RegistryObject<Block> BRAINS = REGISTRY.register("brains", () -> new BrainsBlock());
	public static final RegistryObject<Block> CLAY = REGISTRY.register("clay", () -> new ClayBlock());
	public static final RegistryObject<Block> CLOUD = REGISTRY.register("cloud", () -> new CloudBlock());
	public static final RegistryObject<Block> SMOOTHCOBBLESTONE = REGISTRY.register("smoothcobblestone", () -> new SmoothcobblestoneBlock());
	public static final RegistryObject<Block> CORRUPTDIRT = REGISTRY.register("corruptdirt", () -> new CorruptdirtBlock());
	public static final RegistryObject<Block> DIRESTONE = REGISTRY.register("direstone", () -> new DirestoneBlock());
	public static final RegistryObject<Block> DIRTMATERIAL = REGISTRY.register("dirtmaterial", () -> new DirtmaterialBlock());
	public static final RegistryObject<Block> DRYDIRT = REGISTRY.register("drydirt", () -> new DrydirtBlock());
	public static final RegistryObject<Block> DRYSAND = REGISTRY.register("drysand", () -> new DrysandBlock());
	public static final RegistryObject<Block> FLESHCHUNK = REGISTRY.register("fleshchunk", () -> new FleshchunkBlock());
	public static final RegistryObject<Block> FLESHPILE = REGISTRY.register("fleshpile", () -> new FleshpileBlock());
	public static final RegistryObject<Block> FROZENDIRT = REGISTRY.register("frozendirt", () -> new FrozendirtBlock());
	public static final RegistryObject<Block> THEBLOCK = REGISTRY.register("theblock", () -> new TheblockBlock());
	public static final RegistryObject<Block> GEODECRYSTALS = REGISTRY.register("geodecrystals", () -> new GeodecrystalsBlock());
	public static final RegistryObject<Block> GEODESTONE = REGISTRY.register("geodestone", () -> new GeodestoneBlock());
	public static final RegistryObject<Block> COARSEGRAVEL = REGISTRY.register("coarsegravel", () -> new CoarsegravelBlock());
	public static final RegistryObject<Block> HIVEBLOCK = REGISTRY.register("hiveblock", () -> new HiveblockBlock());
	public static final RegistryObject<Block> ICEMATERIAL = REGISTRY.register("icematerial", () -> new IcematerialBlock());
	public static final RegistryObject<Block> ICEBLOCK = REGISTRY.register("iceblock", () -> new IceblockBlock());
	public static final RegistryObject<Block> JELLYBLOB = REGISTRY.register("jellyblob", () -> new JellyblobBlock());
	public static final RegistryObject<Block> JUNKPILE = REGISTRY.register("junkpile", () -> new JunkpileBlock());
	public static final RegistryObject<Block> LIMESTONE = REGISTRY.register("limestone", () -> new LimestoneBlock());
	public static final RegistryObject<Block> LOOSESILT = REGISTRY.register("loosesilt", () -> new LoosesiltBlock());
	public static final RegistryObject<Block> MAGMAROCK = REGISTRY.register("magmarock", () -> new MagmarockBlock());
	public static final RegistryObject<Block> CORE_LAVA = REGISTRY.register("core_lava", () -> new CoreLavaBlock());
	public static final RegistryObject<Block> METEORITEROCK = REGISTRY.register("meteoriterock", () -> new MeteoriterockBlock());
	public static final RegistryObject<Block> MOON_DUST = REGISTRY.register("moon_dust", () -> new MoonDustBlock());
	public static final RegistryObject<Block> MOONROCK = REGISTRY.register("moonrock", () -> new MoonrockBlock());
	public static final RegistryObject<Block> MOONSTONE = REGISTRY.register("moonstone", () -> new MoonstoneBlock());
	public static final RegistryObject<Block> MUD = REGISTRY.register("mud", () -> new MudBlock());
	public static final RegistryObject<Block> OBSIDIAN = REGISTRY.register("obsidian", () -> new ObsidianBlock());
	public static final RegistryObject<Block> PLANT_MATTER = REGISTRY.register("plant_matter", () -> new PlantMatterBlock());
	public static final RegistryObject<Block> SAND = REGISTRY.register("sand", () -> new SandBlock());
	public static final RegistryObject<Block> ROUGHSANDSTONE = REGISTRY.register("roughsandstone", () -> new RoughsandstoneBlock());
	public static final RegistryObject<Block> SLIME_GLOB = REGISTRY.register("slime_glob", () -> new SlimeGlobBlock());
	public static final RegistryObject<Block> SLUSH = REGISTRY.register("slush", () -> new SlushBlock());
	public static final RegistryObject<Block> SMOOTHICE = REGISTRY.register("smoothice", () -> new SmoothiceBlock());
	public static final RegistryObject<Block> THICKSNOW = REGISTRY.register("thicksnow", () -> new ThicksnowBlock());
	public static final RegistryObject<Block> STONERUBBLE = REGISTRY.register("stonerubble", () -> new StonerubbleBlock());
	public static final RegistryObject<Block> STRIPED_WOOD = REGISTRY.register("striped_wood", () -> new StripedWoodBlock());
	public static final RegistryObject<Block> TAR = REGISTRY.register("tar", () -> new TarBlock());
	public static final RegistryObject<Block> TENTACLE_CLUSTER = REGISTRY.register("tentacle_cluster", () -> new TentacleClusterBlock());
	public static final RegistryObject<Block> VINE_BLOCK = REGISTRY.register("vine_block", () -> new VineBlockBlock());
	public static final RegistryObject<Block> WASTE = REGISTRY.register("waste", () -> new WasteBlock());
	public static final RegistryObject<Block> WET_DIRT = REGISTRY.register("wet_dirt", () -> new WetDirtBlock());
	public static final RegistryObject<Block> WOODEN_LOG = REGISTRY.register("wooden_log", () -> new WoodenLogBlock());
	public static final RegistryObject<Block> YELLOW_GLOW_ROCK = REGISTRY.register("yellow_glow_rock", () -> new YellowGlowRockBlock());
	public static final RegistryObject<Block> UNREFINED_MUDSTONE = REGISTRY.register("unrefined_mudstone", () -> new UnrefinedMudstoneBlock());
	public static final RegistryObject<Block> UNREFINED_ANDESITE = REGISTRY.register("unrefined_andesite", () -> new UnrefinedAndesiteBlock());
	public static final RegistryObject<Block> UNREFINED_DACITE = REGISTRY.register("unrefined_dacite", () -> new UnrefinedDaciteBlock());
	public static final RegistryObject<Block> UNREFINED_GNEISS = REGISTRY.register("unrefined_gneiss", () -> new UnrefinedGneissBlock());
	public static final RegistryObject<Block> UNREFINED_LIMESTONE = REGISTRY.register("unrefined_limestone", () -> new UnrefinedLimestoneBlock());
	public static final RegistryObject<Block> GRANITE_ROCK = REGISTRY.register("granite_rock", () -> new GraniteRockBlock());
	public static final RegistryObject<Block> UNREFINED_CHERT = REGISTRY.register("unrefined_chert", () -> new UnrefinedChertBlock());
	public static final RegistryObject<Block> UNREFINED_GRITSTONE = REGISTRY.register("unrefined_gritstone", () -> new UnrefinedGritstoneBlock());
	public static final RegistryObject<Block> UNREFINED_CONGLOMERATE = REGISTRY.register("unrefined_conglomerate", () -> new UnrefinedConglomerateBlock());
	public static final RegistryObject<Block> UNREFINED_ARKOSE = REGISTRY.register("unrefined_arkose", () -> new UnrefinedArkoseBlock());
	public static final RegistryObject<Block> PACKED_BONES = REGISTRY.register("packed_bones", () -> new PackedBonesBlock());
	public static final RegistryObject<Block> TAR_TEST = REGISTRY.register("tar_test", () -> new TarTestBlock());
	public static final RegistryObject<Block> SLIDY_NOTHING = REGISTRY.register("slidy_nothing", () -> new SlidyNothingBlock());
	public static final RegistryObject<Block> SPACE_FLUID = REGISTRY.register("space_fluid", () -> new SpaceFluidBlock());
}
